// Generated by CoffeeScript 1.3.3
(function() {
  var AttributeFactory, TypeRegister;

  TypeRegister = require('../TypeRegister');

  AttributeFactory = (function() {

    function AttributeFactory() {}

    AttributeFactory.createAttribute = function(attrType, config) {
      var attr;
      attr = TypeRegister.getAttribute(attrType);
      return new attr(config);
    };

    return AttributeFactory;

  })();

  module.exports = AttributeFactory;

}).call(this);
