// Generated by CoffeeScript 1.3.3
(function() {

  exports.AttributeFactory = require('./AttributeFactory');

  exports.Attribute = require('./Attribute');

  exports.Collection = require('./Collection');

  exports.Property = require('./Property');

  exports.Reference = require('./Reference');

}).call(this);
