// Generated by CoffeeScript 1.3.3
(function() {
  var isNodeJS, _resolve;

  isNodeJS = require('detectify').isNodeJS;

  _resolve = function(typeString) {
    var _this;
    if (isNodeJS) {
      _this = this;
    } else {
      _this = window;
    }
    return _this[typeString];
  };

  module.exports = {
    plugins: {},
    registerPlugin: function(type, name, klass) {
      if (this.plugins[type] == null) {
        this.plugins[type] = {};
      }
      this.plugins[type][name] = klass;
      return klass;
    },
    getPlugin: function(type, name) {
      return this.plugins[type][name];
    },
    addModel: function(name, klass) {
      return this.registerPlugin('model', name, klass);
    },
    addAttribute: function(name, klass) {
      return this.registerPlugin('attribute', name, klass);
    },
    getModel: function(name) {
      return this.getPlugin('model', name);
    },
    getAttribute: function(name) {
      return this.getPlugin('attribute', name);
    },
    isModel: function(name) {
      var _ref;
      return ((_ref = this.plugins['model']) != null ? _ref[name] : void 0) != null;
    },
    resolve: function(type) {
      return _resolve(type);
    },
    assertIsType: function(value, type) {
      return type(value) || value;
    }
  };

}).call(this);
