// Generated by CoffeeScript 1.3.3
(function() {
  var $, Ajax, Base,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Base = require('../../core').Base;

  $ = require("jqueryify");

  Ajax = (function(_super) {

    __extends(Ajax, _super);

    function Ajax() {
      return Ajax.__super__.constructor.apply(this, arguments);
    }

    return Ajax;

  })(Base);

}).call(this);
